services:
  # Postgres
  postgres:
    image: postgres:16
    container_name: gong-postgres
    restart: unless-stopped

    # 컨테이너 내부 환경변수
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7
    container_name: gong-redis
    restart: unless-stopped

    ports:
      - "${REDIS_PORT}:6379"

    volumes:
      - redis_data:/data

    # $$ 로 쓴 이유:
    # docker-compose 내부에서 $는 환경변수 치환에 사용되므로 쉘 내부로 실제 $를 넘기기 위해 $$를 사용
    command: >
      sh -c '
      if [ -n "$$REDIS_PASSWORD" ]; then
        redis-server --appendonly yes --requirepass "$$REDIS_PASSWORD";
      else
        redis-server --appendonly yes;
      fi
      '

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: